"""Add phone number

Revision ID: 74752fb569ce
Revises: 05e46f3232a6
Create Date: 2023-04-05 10:42:45.270050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74752fb569ce'
down_revision = '05e46f3232a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
