"""empty message

Revision ID: af09cd511c9f
Revises: 74752fb569ce
Create Date: 2023-04-12 11:41:25.260543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af09cd511c9f'
down_revision = '74752fb569ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
